<?php

define('DATABASE_HOST', $_ENV['DATABASE_HOST']);
define('DATABASE_PORT', $_ENV['DATABASE_PORT']);
define('DATABASE_USERNAME', $_ENV['DATABASE_USERNAME']);
define('DATABASE_PASSWORD', $_ENV['DATABASE_PASSWORD']);
define('DATABASE_NAME', $_ENV['DATABASE_NAME']);